# Custom Language File for Launcher Customizer

[ejs.app]
title = "ApocalyCraft - Launcher"

[ejs.landing]
mediaGitHubURL = "https://apocalycraft.fr"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@ApocalyCraft"
mediaDiscordURL = "https://apocalycraft.fr/discord"

[ejs.settings]
sourceGithubLink = "https://github.com/ApocalyCraft/ApocalyCraft"
supportLink = "https://apocalycraft.fr/launch-support"
